name: robotize
description: Automate your life one script at a time.
homepage: https://github.com/marad/robotize
version: 0.0.1

dependencies:
  ffi: ^0.1.3
  event_bus: ^1.1.0

dev_dependencies:
  test: 

environment:
  sdk: ">=1.8.0 <2.0.0"